---
title: "Interaction Subsets"
author: "Jonathan J. Borrelli"
date: "Thursday, September 17, 2015"
output: 
  html_document:
    toc: true
---

```{r opts, echo = F, message = F}
library(knitr)
opts_chunk$set(message = F, comment = NA, eval = T)
```

Load required libraries:

```{r libraries}
require(ggplot2)
require(reshape2)
require(devtools)
require(igraph)
require(NetIndices)
```

Read in the network datasets, here I am using data from Bascompte et al., Rezende et al., and Ulanowicz. 

```{r data}
basc <- read.csv("./Data/interactionsmarine.csv", header = TRUE, row.names = 1)
rez <- read.csv("./Data/rezendeDATA.csv", header = TRUE)

ULANwebnames<- c("baltic", "charca", "chesapeake", "chesapeakemeso", "crystala", "crystalb", "everglades",
                 "flbay", "lowerches", "middlechesa", "mondego", "narraganset", "rhode", "stmarks", "ythan")
ulan.list <- list()
for(i in 1:15){
  ulan.list[[i]] <- read.csv(paste("./Data/", ULANwebnames[i], ".csv", sep = ""), row.names = 1)
}
names(ulan.list) <- ULANwebnames
```

# Data
Convert initial data into adjacency matrices and graph objects. 

```{r}
basc.mat <- as.matrix(basc)
basc.g <- graph.adjacency(basc.mat, mode = "directed", weighted = TRUE)
# get bascompte edgelist and weights
b.elist <- melt(basc.mat)[melt(basc.mat)[,3] > 0,] 


# get the rows that are interactions
redges <- rez[rez$Int == 1,]
# remove the NA
redges <- redges[-1974,]
# create weighted edgelist
r.elist <- data.frame(pred = as.character(redges$Pred), prey = as.character(redges$Prey), weight = redges$Strength)
# make graph object
rez.g <- graph.edgelist(as.matrix(r.elist[,1:2]))


ulan.graphs <- list()
ulan.mat <- list()
for(i in 1:15){
  ulan.graphs[[i]] <- graph.edgelist(as.matrix(ulan.list[[i]][1:2]))
  ulan.mat[[i]] <- get.adjacency(ulan.graphs[[i]], sparse = F)
}
```

# Graphs

These are not the best images for now. 

```{r bnet}
plot.igraph(basc.g, layout = layout.circle, vertex.size = 1, edge.arrow.size = .25, vertex.label = NA)
```

```{r rnet}
plot.igraph(rez.g, layout = layout.circle, vertex.size = 1, edge.arrow.size = .25, vertex.label = NA)
```

```{r unets, fig.height = 15}
par(mfrow = c(5,3))
for(i in 1:15){
  plot.igraph(ulan.graphs[[i]], layout = layout.circle, vertex.size = 1, edge.arrow.size = .25, vertex.label = NA)
}
```

# Basic network info

Put all networks into a single list

```{r}
all.g <- list(basc.g, rez.g)
for(i in 3:17){
  all.g[[i]] <- ulan.graphs[[i-2]]
}

all.m <- list(basc.mat, rez = get.adjacency(rez.g, sparse = F))
for(i in 3:17){
  all.m[[i]] <- ulan.mat[[i-2]]
}

all.e <- list(b.elist, r.elist)
for(i in 3:17){
  all.e[[i]] <- ulan.list[[i-2]]
}
```

Grab some useful functions to get network properties

```{r}
source_url("https://raw.github.com/jjborrelli/Ecological-Networks/master/FoodWebs/Rscripts/web_functions.R")
```

```{r}
fw.ind <- get_fw_indices(adj.list = all.m, graphs = all.g, web = c("bascompte", "rezende", ULANwebnames))[,-c(9,10,11)] # something is broked with top/int/bas
fw.ind
```


# Quantiles

```{r}
qmat <- t(sapply(all.e, function(x){quantile(x[,3])}))
```

```{r}
webnames1 <- c("bascompte", "rezende", ULANwebnames)
qnames <- c("75", "50", "25", "0")
names.list <- list()
for(j in 1:length(webnames1)){  
  qvec <- c()
  for(i in 1:4){
    qvec[i] <- paste(webnames1[j], qnames[i], sep = "-")
  }
  names.list[[j]] <- qvec
}
```


```{r}
quantMOT <- function(edge, wname, q){  
  # get quantiles
  q75 <- which(edge[,3] > q[4])
  q50 <- which(edge[,3] > q[3] & edge[,3] <= qmat[4])
  q25 <- which(edge[,3] > q[2] & edge[,3] <= q[3])
  q0 <- which(edge[,3] > 0 & edge[,3] <= q[2])
  # get graphs at quantiles
  g75 <- graph.edgelist(as.matrix(edge[q75,1:2]))
  g50 <- graph.edgelist(as.matrix(edge[q50,1:2]))
  g25 <- graph.edgelist(as.matrix(edge[q25,1:2]))
  g0 <- graph.edgelist(as.matrix(edge[q0,1:2]))
  # list graphs
  glist <- list(g75, g50, g25, g0)
  # get motif counts
  mot <- motif_counter(graph.lists = glist, webs = wname)
  return(mot)
}
```

```{r}
qmot <- list()
for(i in 1:17){
  qmot[[i]] <- quantMOT(all.e[[i]], names.list[[i]], qmat[i,])
}

qmot
```



